### ISSUE TITLE
asking about order or unit 

### ISSUE THREAD

**Issue by gksruf** [scalesim-project/scale-sim-v2#24]
Thanks for your great works.

My question is about unit and order on your code.

1) At cfg file, does Bandwidth means max DRAM bandwidth in GB/s ? What is InterfaceBandwidth: CALC  ?
2)   At BANDWIDTH_REPORT.csv, what does Avg Bandwidth means? GB/s? At 1), bandwidth was set but Avg DRAM BW exceeds 10.
3) Do DRAM and SRAM bandwidth affect on Overall Utilization? What is exact definition of it? Does it differ with Compute utilization? They show same result.
4) How map DW layer on TPU and scale model? It has too low mapping efficient what i expect. (less than 3% at COMPUTE_REPORT.csv )  
5) At DETAILED_ACCESS_REPORT.csv, Does DRAM FilterReads mean number of access on DRAM for weight? or Bytes?

Your works are very helpful. Thanks for again.

**Comment by AnandS09** [comment]
Hi @gksruf , 

Thanks for the kind words and the queries. We are working on documenting the tool so that most of the queries like you had could be looked up. 
Meanwhile, please find the answers below.

> 1. At cfg file, does Bandwidth means max DRAM bandwidth in GB/s ? What is InterfaceBandwidth: CALC ?
This is a good question. The units for bandwidth in the tool is words/cycle. You can convert this into conventional units like GB/s by accounting for your system word size and frequency.

CALC and USER are two modes in which the tool works for bandwidths.
CALC : Calculate the average interface bandwidth per operand. This mode ignores the user provided bandwidth
USER: Use the max bandwidth provided in the cfg file 


> 2. At BANDWIDTH_REPORT.csv, what does Avg Bandwidth means? GB/s? At 1), bandwidth was set but Avg DRAM BW exceeds 10.

For the unit of the reported bandwidth, it is words/cycle as mentioned above. I think the issue you mentioned with Avg DRAM BW will go away if you use `InterfaceBandwidth: USER`


>3. Do DRAM and SRAM bandwidth affect on Overall Utilization? What is exact definition of it? Does it differ with Compute utilization? They show same result.

Max SRAM bandwidth is fixed for a given array and is determined by the array dimensions. In USER mode the DRAM bandwidth will play a role in Overall Utilization as insufficient bandwidth will lead to stalls which will lead to decreased utilization.


>4.How map DW layer on TPU and scale model? It has too low mapping efficient what i expect. (less than 3% at COMPUTE_REPORT.csv )

We are working on this and tracking it with #9 


>5. At DETAILED_ACCESS_REPORT.csv, Does DRAM FilterReads mean number of access on DRAM for weight? or Bytes?

It is the number of accesses to the DRAM for filters, where each element is one word long. The default word size in scale-sim is 1 Byte. We do not support user provided word sizes yet, but we might do that in the future. 


I hope you find these helpful.

**Comment by gksruf** [comment]
Thanks for your kindness.

At cfg file,
IfmapSramSzkB:    6144
FilterSramSzkB:   6144
OfmapSramSzkB:    2048
means that the processor SRAM size is (6144 + 6144 + 2048)?

At cfg of eyeriss, the sram size of (IA, W, OA) are 108, 108, 108 but eyeriss has only 108KB.
Moreover eyeriss has its register files in PE each. How the simulator handles it?
