### ISSUE TITLE
Scale-sim-v2 does not give "cycle accurate simulation"

### ISSUE THREAD

**Issue by Z-KN** [scalesim-project/scale-sim-v2#70]
According to the code, the total cycle is advanced like this
```Python
    def get_total_cycles(self):
        assert self.all_layer_run_done, 'Layer runs are not done yet'

        total_cycles = 0
        for layer_obj in self.single_layer_sim_object_list:
            cycles_this_layer = int(layer_obj.get_compute_report_items[0])
            total_cycles += cycles_this_layer

        return total_cycles
```
Consequently, it does not provide the behavior of each cycle, right? The simulator only "computes" the cycles to be spent, not "simulates" across each cycle.

**Comment by ritikraj7** [comment]
Hi @Z-KN,  the tool does simulate the behavior of each cycle. Please refer to the SRAM and DRAM traces. They contain the addresses accessed in each clock cycle by SRAM and DRAM respectively.  Since systolic array is deterministic, the memory behavior enables us to compute performance and utilization.
