### ISSUE TITLE
How to understand cycle-accurate SRAM/DRAM access logs

### ISSUE THREAD

**Issue by lllbbbyyy** [scalesim-project/scale-sim-v2#75]
I'm trying to integrate with other systems through accurate DRAM access logs, but I'm now confused about the content of the associated logs. Could you please explain me briefly how to read the output of these trace logs, or where I can find an introduction to them?

**Comment by ritikraj7** [comment]
Hi @lllbbbyyy, three DRAM trace files are generated by the tool-
+ filter DRAM trace
+ ifmap DRAM trace
+ ofmap DRAM trace
The first column in these traces represents clock cycle. You might notice negative clock cycles in filter and ifmap DRAM traces. That is because of prefetching and we assume clock cycle 0 to mark the start of calculation, which happens after prefetching. The rest of the columns represent addresses. You can distinguish between filter, ifmap and ofmap addresses using the address offset values specified in the config file. The value '-1' represents empty address, i.e., no actual address was accessed in that cycle.
